version: '3'
services:
  db:
    image: mariadb
    container_name: fanciedarts-db
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "10736:3306"
    env_file: ./db.env
    environment:
      MYSQL_ROOT_PASSWORD: z

  wordpress:
    depends_on:
      - db
    build: ./wordpress
    image: fanciedarts/web
    container_name: fanciedarts-web
    volumes:
      # - ./wordpress/php/xdebug.ini://usr/local/etc/php/conf.d/xdebug.ini
      - ./app/fanciedarts:/var/www/html/fanciedarts
    ports:
      - "10780:80"
    # environment:
      # XDEBUG_CONFIG: "remote_host={host_ip}"
