version: '3'
services:
  db:
    image: mariadb
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    env_file: ./db.env
    environment:
      MYSQL_ROOT_PASSWORD: z

  wordpress:
    depends_on:
      - db
    build: ./wordpress
    volumes:
      # - ./wordpress/php/xdebug.ini://usr/local/etc/php/conf.d/xdebug.ini
      - ./backup:/tmp/wordpress/data
      - ./entrypoint-initapp.sh:/tmp/wordpress/entrypoint-initapp.sh
      - ./tools/rewrite_after_upgrade.php:/tmp/wordpress/rewrite_after_upgrade.php
      - ./app:/var/www/html
    ports:
      - "80:80"
    env_file: ./wordpress.env
    environment:
      WORDPRESS_DB_HOST: db:3306
      # XDEBUG_CONFIG: "remote_host={host_ip}"
