version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    restart: always
    env_file: ./db.env
    environment:
      MYSQL_ROOT_PASSWORD: z

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./backup:/tmp/fanciedarts/data
      - ./entrypoint-initapp.sh:/tmp/fanciedarts/entrypoint-initapp.sh
      - ./app:/var/www/html
    ports:
      - "80:80"
    env_file: ./wordpress.env
    environment:
      WORDPRESS_DB_HOST: db:3306
