<?php
/****************************************************************
//Default theme options for visual.
****************************************************************/
$def_visual = array(
	'base_font_color'			=> '#444444',
	'base_font_size'			=> 14,
	'base_font_size_unit'		=> 'px',
	'base_font_size_mb'			=> 14,
	'base_font_size_mb_unit'	=> 'px',
	'base_link_color'			=> '#ff91a2',
	'base_link_hover_color'		=> '#ff6e90',
	'base_link_underline'    	=> '1',
	'base_link_bold'			=> false,
	'base_font_family'			=> 'default',
	'base_font_weight'			=> 200,
	'container_bg_color'		=> '#ffffff',
	'site_bg_color'				=> '#f4f4f4',
	'dp_column'					=> "2",
	'dp_1column_only_top'		=> false,
	'header_menu_link_color'  	=> '#6a6a6a',
	'header_menu_link_hover_color'  => '#444444',
	'header_menu_bgcolor'			=> '#ffffff',
	'header_banner_font_color'	=> '#ffffff',
	'header_banner_text_shadow_enable'	=> true,
	'header_banner_text_shadow_color'	=> '#000000',
	'dp_header_content_type'	=> 1,
	'dp_number_of_slideshow'	=> 7,
	'dp_slideshow_target'		=> 'header_img',
	'dp_slideshow_target_mobile'=> 'header_img',
	'dp_slideshow_order'		=> 'random',
	'dp_slideshow_effect'		=> 'fade',
	'dp_slideshow_speed'		=> 3000,
	'dp_slideshow_transition_time'	=> 1400,
	'dp_slideshow_nav_button'	=> false,
	'dp_slideshow_control_button' => false,
	'dp_slideshow_post_show_meta_always' => false,
	'dp_header_content_type_mobile'		=> 'none',
	'dp_number_of_slideshow_mobile'		=> 4,
	'dp_slideshow_order_mobile'			=> 'normal',
	'dp_slideshow_effect_mobile'		=> 'fade',
	'dp_slideshow_speed_mobile'			=> 4000,
	'dp_slideshow_transition_time_mobile'	=> 3000,
	'fullscreen_video_url'		=> '',
	'fullscreen_video_start'	=> 0,
	'h1title_as_what'			=> 'text',
	'dp_title_img'				=> '',
	'dp_title_img_mobile'		=> '',
	'dp_header_img'				=> 'random',
	'dp_header_img_mobile'		=> 'random',
	'dp_background_img'			=> '',
	'dp_background_repeat'		=> 'repeat-y',
	'dp_theme_sidebar'			=> 'right',
	'original_css'				=> '',
	'cat_colors'				=> array(),
	'cat_ids'					=> array(),
	'global_menu_pos'			=> 'top',
	'footer_bgcolor'			=> '#3d3d3d',
	'footer_col_number'			=> 3,
	'footer_text_color'			=> '#efefef',
	'footer_link_color'			=> '#ffffff',
	'footer_link_hover_color'	=> '#efefef',
	'accent_color'				=> '#ff91a2'
);
?>